# Generated by Django 3.1.4 on 2021-04-20 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_bookstore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='is_Closed',
        ),
        migrations.AddField(
            model_name='todo',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
    ]
