# Generated by Django 3.1.4 on 2021-04-20 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20210420_2123'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='is_Closed',
            new_name='is_closed',
        ),
    ]
